version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    environment:
      - TZ=Europe/Berlin
    ports:
      - "55870:55870"
      - "55871:55871"
      - "55872:55872"
    volumes:
      - shopware55_php72:/var/www/shopware55_php72:delegated
      - shopware55_php71:/var/www/shopware55_php71:delegated
      - shopware55_php70:/var/www/shopware55_php70:delegated
      - shopware55_php56:/var/www/shopware55_php56:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/include.shopware.conf:/etc/nginx/include.shopware.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - shopware55_php72
      - shopware55_php71
      - shopware55_php70
      - shopware55_php56
      - mysql
    depends_on:
      - shopware55_php72
      - shopware55_php71
      - shopware55_php70
      - shopware55_php56

  shopware55_php72:
    image: solutiondrive/docker-shopware-container:shopware5.5.2-php7.2
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware55_php72
      - WEB_HOST=localhost:55872
    volumes:
      - shopware55_php72:/var/www/shopware55_php72:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
      - mailhog
    depends_on:
      - mysql
      - mailhog

  shopware55_php71:
    image: solutiondrive/docker-shopware-container:shopware5.5.2-php7.1
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware55_php71
      - WEB_HOST=localhost:55871
    volumes:
      - shopware55_php71:/var/www/shopware55_php71:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
      - mailhog
    depends_on:
      - mysql
      - mailhog

  shopware55_php70:
    image: solutiondrive/docker-shopware-container:shopware5.5.2-php7.0
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware55_php70
      - WEB_HOST=localhost:55870
    volumes:
      - shopware55_php70:/var/www/shopware55_php70:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
      - mailhog
    depends_on:
      - mysql
      - mailhog

  shopware55_php56:
    image: solutiondrive/docker-shopware-container:shopware5.5.2-php5.6
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware55_php56
      - WEB_HOST=localhost:55856
    volumes:
      - shopware55_php56:/var/www/shopware55_php70:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
      - mailhog
    depends_on:
      - mysql
      - mailhog

  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DATABASE=test
    ports:
      - "55331:3306"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8055:8025"

volumes:
  shopware55_php72:
  shopware55_php71:
  shopware55_php70:
  shopware55_php56:
