version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    environment:
      - TZ=Europe/Berlin
    ports:
      - "57874:57874"
      - "57880:57880"
      - "57881:57881"
    volumes:
      - shopware57_php74:/var/www/shopware57_php74:delegated
      - shopware57_php80:/var/www/shopware57_php80:delegated
      - shopware57_php81:/var/www/shopware57_php81:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/include.shopware.conf:/etc/nginx/include.shopware.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - shopware57_php74
      - shopware57_php80
      - shopware57_php81
      - mysql
    depends_on:
      - shopware57_php74
      - shopware57_php80
      - shopware57_php81

  shopware57_php74:
    image: solutiondrive/docker-shopware-container:shopware5.7.7-php7.4
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware57_php74
      - WEB_HOST=localhost:57874
    volumes:
      - shopware57_php74:/var/www/shopware57_php74:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware57_php80:
    image: solutiondrive/docker-shopware-container:shopware5.7.7-php8.0
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware57_php80
      - WEB_HOST=localhost:57880
    volumes:
      - shopware57_php80:/var/www/shopware57_php80:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware57_php81:
    image: solutiondrive/docker-shopware-container:shopware5.7.7-php8.1
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware57_php81
      - WEB_HOST=localhost:57881
    volumes:
      - shopware57_php81:/var/www/shopware57_php81:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DATABASE=test
    ports:
      - "56331:3306"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8055:8025"

volumes:
  shopware57_php74:
  shopware57_php80:
  shopware57_php81:
