version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    environment:
      - TZ=Europe/Berlin
    ports:
      - "53856:53856"
      - "53870:53870"
      - "53871:53871"
      - "53872:53872"
      - "53873:53873"
    volumes:
      - shopware53_php73:/var/www/shopware53_php73:delegated
      - shopware53_php72:/var/www/shopware53_php72:delegated
      - shopware53_php71:/var/www/shopware53_php71:delegated
      - shopware53_php70:/var/www/shopware53_php70:delegated
      - shopware53_php56:/var/www/shopware53_php56:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/include.shopware.conf:/etc/nginx/include.shopware.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - shopware53_php73
      - shopware53_php72
      - shopware53_php71
      - shopware53_php70
      - shopware53_php56
      - mysql
    depends_on:
      - shopware53_php73
      - shopware53_php72
      - shopware53_php71
      - shopware53_php70
      - shopware53_php56

  shopware53_php73:
    image: solutiondrive/docker-shopware-container:shopware5.3.7-php7.3
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware53_php73
      - WEB_HOST=localhost:53873
    volumes:
      - shopware53_php73:/var/www/shopware53_php73:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware53_php72:
    image: solutiondrive/docker-shopware-container:shopware5.3.7-php7.2
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware53_php72
      - WEB_HOST=localhost:53872
    volumes:
      - shopware53_php72:/var/www/shopware53_php72:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware53_php71:
    image: solutiondrive/docker-shopware-container:shopware5.3.7-php7.1
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware53_php71
      - WEB_HOST=localhost:53871
    volumes:
      - shopware53_php71:/var/www/shopware53_php71:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware53_php70:
    image: solutiondrive/docker-shopware-container:shopware5.3.7-php7.0
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware53_php70
      - WEB_HOST=localhost:53870
    volumes:
      - shopware53_php70:/var/www/shopware53_php70:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware53_php56:
    image: solutiondrive/docker-shopware-container:shopware5.3.7-php5.6
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware53_php56
      - WEB_HOST=localhost:53856
    volumes:
      - shopware53_php56:/var/www/shopware53_php56:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DATABASE=test
    ports:
      - "53331:3306"

volumes:
  shopware53_php73:
  shopware53_php72:
  shopware53_php71:
  shopware53_php70:
  shopware53_php56:
