version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    environment:
      - TZ=Europe/Berlin
    ports:
      - "56872:56872"
      - "56873:56873"
    volumes:
      - shopware56_php72:/var/www/shopware56_php72:delegated
      - shopware56_php73:/var/www/shopware56_php73:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/include.shopware.conf:/etc/nginx/include.shopware.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - shopware56_php72
      - shopware56_php73
      - mysql
    depends_on:
      - shopware56_php72
      - shopware56_php73

  shopware56_php72:
    image: solutiondrive/docker-shopware-container:shopware5.6.7-php7.2
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware56_php72
      - WEB_HOST=localhost:56872
    volumes:
      - shopware56_php72:/var/www/shopware56_php72:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware56_php73:
    image: solutiondrive/docker-shopware-container:shopware5.6.7-php7.3
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware56_php73
      - WEB_HOST=localhost:56873
    volumes:
      - shopware56_php73:/var/www/shopware56_php73:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DATABASE=test
    ports:
      - "56331:3306"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8055:8025"

volumes:
  shopware56_php72:
  shopware56_php73:
