version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    environment:
      - TZ=Europe/Berlin
    ports:
      - "52870:52870"
      - "52871:52871"
      - "52872:52872"
    volumes:
      - shopware52_php72:/var/www/shopware52_php72:delegated
      - shopware52_php71:/var/www/shopware52_php71:delegated
      - shopware52_php70:/var/www/shopware52_php70:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/include.shopware.conf:/etc/nginx/include.shopware.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - shopware52_php72
      - shopware52_php71
      - shopware52_php70
      - mysql
    depends_on:
      - shopware52_php72
      - shopware52_php71
      - shopware52_php70

  shopware52_php72:
    image: solutiondrive/docker-shopware-container:shopware5.4.6-php7.2
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware52_php72
      - WEB_HOST=localhost:52872
    volumes:
      - shopware52_php72:/var/www/shopware52_php72:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware52_php71:
    image: solutiondrive/docker-shopware-container:shopware5.4.6-php7.1
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware52_php71
      - WEB_HOST=localhost:52871
    volumes:
      - shopware52_php71:/var/www/shopware52_php71:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  shopware52_php70:
    image: solutiondrive/docker-shopware-container:shopware5.4.6-php7.0
    environment:
      - TZ=Europe/Berlin
      - DB_DATABASE=shopware52_php70
      - WEB_HOST=localhost:52870
    volumes:
      - shopware52_php70:/var/www/shopware52_php70:delegated
      - ${PROJECT_DIR}:/opt/host:delegated
      - ./php/php.ini:/usr/local/etc/php/conf.d/zzz-override-php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DATABASE=test
    ports:
      - "52331:3306"

volumes:
  shopware52_php72:
  shopware52_php71:
  shopware52_php70:
